sudo: false
language: node_js
node_js: 10
addons:
  chrome: stable
script:
  - npm run build
  - npm run lint
  - npm run bundlesize
  - npm run test:ci
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - npm run ghpages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GH_TOKEN
  on:
    branch: master
notifications:
  email:
    on_success: never
    on_failure: change
