language: node_js
node_js:
  - 10

script:
  - npm run lint
  - npm run test:ci
  - npm run build

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - npm run build:docs

jobs:
  include:
    - stage: release
      node_js: 10
      script:
        - npm run build
        - npm run semantic-release

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GH_TOKEN
  on:
    branch: master

notifications:
  email: false
